### PR TITLE
Extend SendPresence() stub func to allow send useful statuses

### PR DESCRIPTION
**Pull request by eleksir**
Make use of Presence.{Type,Show,Status} fields in SendPresence() to send actual client status to server and chat rooms.

### CODE REVIEW

**Comment by mattn** [comment]
@mdosch Could you please handle this?

**Comment by mdosch** [comment]
Will have a look when I find the time. @eleksir can you fix the conflict in the meantime?

**Comment by Neustradamus** [comment]
@eleksir: Have you seen the @mdosch comment?

**Comment by eleksir** [comment]
@Neustradamus aha. Done.
@mdosch no conflicts now, you can review change and merge if all seems good.

**Comment by eleksir** [comment]
Forgot to fix one thing while rebase change. Now it should be okay.

**Comment by mdosch** [comment]
Thanks, I hope I will find time soon to look at this.

**Review by mdosch — APPROVED** [review]

**Pull request merged**
